### ISSUE TITLE
Document Mutability - toMutable() method is missing

### ISSUE THREAD

**Issue by azaddhirajkumar** [Couchbase-Ecosystem/cbl-ionic#16]
By default, a document is immutable when it is read from the database. The `toMutable()` method should create an updatable instance of the document.

We should have a toMutable() method in Document just like we have for swift: 
https://docs.couchbase.com/couchbase-lite/current/swift/document.html#mutability

**Comment by biozal** [comment]
@azaddhirajkumar please update this to include more information about the issue.

**Comment by biozal** [comment]
This method is provided in the MutableDocument.fromDocument method here:  https://github.com/Couchbase-Ecosystem/cblite-js/blob/main/cblite/src/mutable-document.ts#L61
