### ISSUE TITLE
Document's getBoolean(), getInt(), getFloat(), getDouble(), getLong(), getString(), getDate() does not return a default value

### ISSUE THREAD

**Issue by azaddhirajkumar** [Couchbase-Ecosystem/cbl-ionic#25]
These methods are just retrieving whatever is stored in the DB. They are not returning any default value.

For example: 

`getInt()` is expected to return `0` when attempting to retrieve a value that is not stored as an integer.

If a field is set with `setString('stringPunk', "Jett")`, 
retrieving this field using `getInt("stringPunk")` should return `0`, as the stored value is a string, not an integer.

**Comment by biozal** [comment]
@azaddhirajkumar  Please write up more information on this bug report.

**Comment by biozal** [comment]
this was fixed with the last update
