### ISSUE TITLE
App crashes when collection_GetDocument is called with blob attachment

### ISSUE THREAD

**Issue by brydecena** [Couchbase-Ecosystem/cbl-ionic#43]
**Describe the bug**
We migrated an app from 2.x couchbaselite plugin, we are experiencing a crash on the app when 'collection_GetDocument' is called on some areas, after investigating it seems these documents have attachments on it, other 'collection_GetDocument' are returning successfully probably because they don't have an attachment.
See image below of XCode logs:
<img width="726" alt="Screenshot 2024-06-16 at 3 00 08 PM" src="https://github.com/Couchbase-Ecosystem/cbl-ionic/assets/166391797/c6d8eef2-cc33-45bb-9dfd-f564a1ec319b">

**Expected behavior**
'collection_GetDocument' should return a response from the plugin

**Current behavior**
App crashes, seems like the crash is happening on this line:
<img width="720" alt="Screenshot 2024-06-16 at 3 06 58 PM" src="https://github.com/Couchbase-Ecosystem/cbl-ionic/assets/166391797/9e0c8a83-53ba-4af1-9313-4840e7a2f396">

**Plugin Version**
3.x

**Affected Platforms (please complete the following information):**
 - Device: [iPad simulator]
 - OS: [e.g. iOS17.4]

**Comment by biozal** [comment]
@brydecena 

Can you provide me more details like what kind of attachments, how large are they, and what content type are they set to so I can setup something to try and reproduce the issue.

Thanks - Aaron

**Comment by biozal** [comment]
Using the Example App Get Document page I was able to get back a document with an attachment on it without it crashing, so I'm going to need more details on what your document looks like:

![document_with_attachment](https://github.com/Couchbase-Ecosystem/cbl-ionic/assets/80424345/a9a7cbb3-f5f4-4bab-b9dd-b83e0c7b01fc)

**Comment by biozal** [comment]
Adding to this - here is the Swift behind the scene's break points on this call - here is a breakpoint on the documentAs Map function call:
<img width="751" alt="image" src="https://github.com/Couchbase-Ecosystem/cbl-ionic/assets/80424345/015d0a8c-6b6a-466f-b1a9-38363bea9342">

Adding a break point to the code that pulls the blob properties showing it’s properly pulling out the blob properties:
<img width="917" alt="image" src="https://github.com/Couchbase-Ecosystem/cbl-ionic/assets/80424345/ca3a2a0e-7673-4062-b5f2-55984f4c9212">

Finally the method returning properly:
<img width="936" alt="image" src="https://github.com/Couchbase-Ecosystem/cbl-ionic/assets/80424345/30cecf5b-68fc-40f4-8539-ccfa4ce3fc74">


No where can I see this code crashing or breaking with our without blobs.

**Comment by brydecena** [comment]
Hi @biozal ,
This is the logs I got from their app using the old plugin they had:
Please see files/attachments of this document:
{
"_attachments":{
"thumbnail-rider.jpg":{
"stub":true,
"length":122156,
"digest":"sha1-x0DKluwjDwyURWhqzdyV5FdpHzQ=",
"revpos":441,
"content_type":"image/jpeg"
},
"econnectPrestige_2210(TC).pdf":{
"stub":true,
"length":3447130,
"digest":"sha1-UnXEWfNXCviiBH6rnpBPsVbKyPA=",
"revpos":419,
"content_type":"application/pdf"
},
"premrefund_2401(TC).pdf":{
"stub":true,
"length":611964,
"digest":"sha1-iNNh0ou2XEYiQ4ll4aDwaxHb34Q=",
"revpos":449,
"content_type":"application/pdf"
},
"VHIS-MC-TC-discount-2207(SC).pdf":{
"stub":true,
"length":1563851,
"digest":"sha1-LkqLp1rqDCJykIMSeCPW0Lo0ct8=",
"revpos":409,
"content_type":"application/pdf"
},
"brochure-rider-SC.pdf":{
"stub":true,
"length":5102666,
"digest":"sha1-m5/13VFN+8iM2QO8iH38P3NB4Bc=",
"revpos":430,
"content_type":"application/pdf"
},
"brochure-EN.pdf":{
"stub":true,
"length":4989384,
"digest":"sha1-PNB/h2tFPxcqIEOraHuhIX9ZMfA=",
"revpos":444,
"content_type":"application/pdf"
},
"econnectPrestige_2210(EN).pdf":{
"stub":true,
"length":3688350,
"digest":"sha1-l6NfdHQFosfE7QNNHcQ0OqGtp5U=",
"revpos":417,
"content_type":"application/pdf"
},
"brochure-rider-EN.pdf":{
"stub":true,
"length":4988404,
"digest":"sha1-tfaWi1inXgbksEjyqHI1V7wWQ5M=",
"revpos":429,
"content_type":"application/pdf"
},
"VHIS-MC-TC-discount-2207(EN).pdf":{
"stub":true,
"length":1382603,
"digest":"sha1-SY8q45adKbd4xI4N4YrGjCxBonE=",
"revpos":408,
"content_type":"application/pdf"
},
"pioneer_flyer-2001(EN).pdf":{
"stub":true,
"length":244615,
"digest":"sha1-JYWOJaNsxjz1GzbQIPntF89FDB0=",
"revpos":399,
"content_type":"application/pdf"
},
"premrefund_2311(EN).pdf":{
"stub":true,
"length":381373,
"digest":"sha1-VP1uVmYZwU6unItkaHQXkZYf0aA=",
"revpos":438,
"content_type":"application/pdf"
},
"VHIS-MC-TC-discount-2207(TC).pdf":{
"stub":true,
"length":1655996,
"digest":"sha1-FRXbaTRS1eas5R3UsAidSIWHG5I=",
"revpos":410,
"content_type":"application/pdf"
},
"rider_flyer2207(SC).pdf":{
"stub":true,
"length":1037342,
"digest":"sha1-SjI/tEuJBfmbPxwu3SUcV4DXB+I=",
"revpos":414,
"content_type":"application/pdf"
},
"VHIS-MC-TC-discount-2201(SC).pdf":{
"stub":true,
"length":1312180,
"digest":"sha1-Q66xyTRJMkUs7dz0Em6l869pA/o=",
"revpos":385,
"content_type":"application/pdf"
},
"rider_flyer2207(TC).pdf":{
"stub":true,
"length":1016689,
"digest":"sha1-nxtFc8XEG1xGdhg+4YFjccU8Vto=",
"revpos":415,
"content_type":"application/pdf"
},
"brochure-TC.pdf":{
"stub":true,
"length":5088729,
"digest":"sha1-av17bX4ahJDljrSaXVioPoXxey8=",
"revpos":446,
"content_type":"application/pdf"
},
"premrefund_2401(EN).pdf":{
"stub":true,
"length":617625,
"digest":"sha1-zi20tT0OpYw5Us6WDVpHqG7OWfc=",
"revpos":447,
"content_type":"application/pdf"
},
"thumbnail.jpg":{
"stub":true,
"length":121170,
"digest":"sha1-f+dGVtUYuCx4yJOqo3Apg6PRbWQ=",
"revpos":442,
"content_type":"image/jpeg"
},
"VHIS-MC-TC-discount-2201(EN).pdf":{
"stub":true,
"length":1108994,
"digest":"sha1-qRv0jYIv6NzQ8pCf/CjLhKHzV+8=",
"revpos":384,
"content_type":"application/pdf"
},
"premrefund_2311(SC).pdf":{
"stub":true,
"length":455135,
"digest":"sha1-bAitW76ygr3XK8zxhxeY74+wgCo=",
"revpos":439,
"content_type":"application/pdf"
},
"VHIS-MC-TC-discount-2201(TC).pdf":{
"stub":true,
"length":1404299,
"digest":"sha1-Rm//Dgh5faKphQ2NTNd/fLBE5ug=",
"revpos":386,
"content_type":"application/pdf"
},
"brochure-rider-TC.pdf":{
"stub":true,
"length":5140680,
"digest":"sha1-+kBEISFe1nBScnadXP8eJH8NYfY=",
"revpos":431,
"content_type":"application/pdf"
},
"econnectPrestige_2311(SC).pdf":{
"stub":true,
"length":1144656,
"digest":"sha1-PLkPbRKVGTY4NXJnNUrEfcvyqdY=",
"revpos":436,
"content_type":"application/pdf"
},
"econnectPrestige_2311(TC).pdf":{
"stub":true,
"length":1177464,
"digest":"sha1-CzncjAZQPMJ5vHYFTZpHJ/Hi9zg=",
"revpos":437,
"content_type":"application/pdf"
},
"brochure-SC.pdf":{
"stub":true,
"length":5073145,
"digest":"sha1-xmGo/Q7klVCIpTfb2GcKTsHWShM=",
"revpos":445,
"content_type":"application/pdf"
},
"pioneer_flyer-2001(SC).pdf":{
"stub":true,
"length":352836,
"digest":"sha1-lG57Q+78OvsYS+6W+MQSkZfCNhU=",
"revpos":400,
"content_type":"application/pdf"
},
"pioneer_flyer-2001(TC).pdf":{
"stub":true,
"length":365520,
"digest":"sha1-y/qzJfxZub91oGkxc4e90DUhMfc=",
"revpos":401,
"content_type":"application/pdf"
},
"premrefund_2311(TC).pdf":{
"stub":true,
"length":448879,
"digest":"sha1-ntXydREjWfTEBUjFzOQ7hlXiykI=",
"revpos":440,
"content_type":"application/pdf"
},
"rider_flyer2207(EN).pdf":{
"stub":true,
"length":1793093,
"digest":"sha1-7ZfixAvRjEkrv1v+8U/qG5g498c=",
"revpos":413,
"content_type":"application/pdf"
},
"econnectPrestige_2311(EN).pdf":{
"stub":true,
"length":1086779,
"digest":"sha1-XEG2UKMsVYQAYxypjli2DxDbKNM=",
"revpos":435,
"content_type":"application/pdf"
},
"premrefund_2401(SC).pdf":{
"stub":true,
"length":618282,
"digest":"sha1-vvCybMqe/GP459vlxUkOEQvilfA=",
"revpos":448,
"content_type":"application/pdf"
},
"econnectPrestige_2210(SC).pdf":{
"stub":true,
"length":3266141,
"digest":"sha1-6vSzLQhbl842sbnpig01nI6vqRw=",
"revpos":418,
"content_type":"application/pdf"
}
}
}

**Comment by biozal** [comment]
Release 0.1.9 fixes issues with getting blob content and we don't see any issues with pulling documents that have attachments as shown in screen shots.

**Comment by brydecena** [comment]
Hi @biozal ,
The crash is happening here when converting the document to dictionary.
<img width="454" alt="Screenshot 2024-06-17 at 9 26 48 PM" src="https://github.com/Couchbase-Ecosystem/cbl-ionic/assets/166391797/13c8d296-5080-4656-aab2-97a888675923">

Also, please note that the document was obtained from a **sync**, maybe that made the difference, I believe what you are testing is you created a document and attached the file/blob and then get that document that you created, maybe that's why you have the expected format/value and did not had any error on your testing?

Or probably there is also something on our blob/attachment that was not processed in making a doc or converting it to dictionary.

I try will send you our database/attachment that was created, hope you can test it out.
Thanks!
