### ISSUE TITLE
Passing an empty config on replicator_Create does not return a replicatorId and cannot proceed to sync

### ISSUE THREAD

**Issue by brydecena** [Couchbase-Ecosystem/cbl-ionic#45]
**Describe the bug**
Replicator syncing should still work when passing an empty config(document and channel), but you cannot create a replicator if you pass an empty config.

**Expected behavior**
Syncing or creating a replicator should still proceed.

**Current behavior**
Cannot create a replicator as its having the issue below:
<img width="984" alt="Screenshot 2024-06-16 at 10 10 41 PM" src="https://github.com/Couchbase-Ecosystem/cbl-ionic/assets/166391797/be9131b6-bfb2-4ef6-be49-a0ac75ae5f74">

**Params passed on replicator_Create native sdk:**
{"config":{"authenticator":{"type":"session","data":{"cookieName":"SyncGatewaySession","sessionID":"9e9986bad1ef2d38eacfb17d253341510f8ba12f"}},"target":{"url":"wss://pos2.uatctflife.com.hk/uat5gw/agent_db"},"replicatorType":"PUSH_AND_PULL","continuous":true,"acceptParentDomainCookies":false,"acceptSelfSignedCerts":true,"allowReplicationInBackground":false,"autoPurgeEnabled":true,"heartbeat":300,"maxAttempts":10,"maxAttemptWaitTime":300,"collectionConfig":"[{\"collections\":[{\"collection\":{\"name\":\"_default\",\"scopeName\":\"_default\",\"databaseName\":\"agent_db\"}}],\"config\":{\"channels\":[\"\"],\"documentIds\":[\"\"]}}]"}}

**Plugin Version**
3.x

**Affected Platforms (please complete the following information):**
 - Device: [iPad]
 - OS: [iOS17.4]

**Comment by khanium** [comment]
You can close this issue, it is solved when pass empty array to channels or documentIds properties. An improvement would be to have a default empty value in case those properties are missing.
